### ISSUE TITLE
Allow creating AMMs if only one token pair has an existing balance

### ISSUE THREAD

**Issue by schmanu** [cowprotocol/cow-amm#58]
In the current implementation it is not possible to create an AMM if [either balance of the token pair is 0](https://github.com/cowprotocol/cow-amm/blob/main/src/CowAmmModule.sol#L225).

This makes it impossible to deploy an AMM and only supply one side of the token pair to trigger an Order which balances the supply and forces users to first submit an order before creating an AMM.

**Comment by mfw78** [comment]
The [new standalone CoWAMM contract](https://github.com/cowprotocol/cow-amm/blob/4615cf8b80786e4de1d76cd1ad41f69353c0b797/src/ConstantProductFactory.sol) that's currently pending audit will solve this issue. Initially as we were testing, we wanted to prevent obvious inadvertent foot-gun issues :smiley:

**Comment by mfw78** [comment]
Fixed by #44
